environment:
  VENV: "%APPVEYOR_BUILD_FOLDER%\\venv"

  matrix:
    - TOXENV: py27
    - TOXENV: py34
    - TOXENV: py35
    - TOXENV: py36
    - TOXENV: py37
    - TOXENV: wheel

# https://www.appveyor.com/docs/how-to/rdp-to-build-worker/
init:
  - ps: if (Get-ChildItem Env:ENABLE_RDP -ErrorAction SilentlyContinue) {iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))} else {echo RDP not enabled}
  - echo "TOXENV- %TOXENV%"

install:
  - virtualenv -p "%PYTHON%\\python.exe" "%VENV%"
  - "%VENV%\\Scripts\\activate"
  - pip install -r requirements.tox.txt
  - ps: Update-AppveyorBuild -Version "v$(python get_version.py) b$Env:APPVEYOR_BUILD_NUMBER"

build_script:
  - tox

artifacts:
  - path: "dist\\*.whl"

# https://www.appveyor.com/docs/how-to/rdp-to-build-worker/
on_finish:
  - ps: if (Get-ChildItem Env:ENABLE_RDP -ErrorAction SilentlyContinue) {$blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))} else {echo RDP not enabled}
